library(shiny)
library(shinythemes)
library(shinydashboard)
library(DT)
library(dplyr)
library(visdat)
library(ggplot2)
library(shinycssloaders)
library(vcd)
library(car)
library(corrgram)
library(RColorBrewer)
library(GGally)
library(Hmisc)
library(tidyr)
library(tabplot)
library(dlookr)
library(naniar)
library(mice)
library(finalfit)
library(caret)
library(glmnet)
library(rpart.plot)
library(recipes)

set.seed(123)
pMiss <- function(x){ sum(is.na(x))/length(x)*100 }

